2010-03-11 12:00:00,[Errno 2] No such file or directory: 'D:\\MSG\\MSG_nat\\batch_3\\HRSEVIRI_20100311T122700Z_20100311T122700Z_epct_fbcd108c_FP.nc'
2011-02-28 12:00:00,'NoneType' object has no attribute '_id'
2011-03-01 12:00:00,'NoneType' object has no attribute '_id'
2011-03-02 12:00:00,'NoneType' object has no attribute '_id'
2012-02-28 12:00:00,'NoneType' object has no attribute '_id'
2012-02-29 12:00:00,'NoneType' object has no attribute '_id'
2012-03-01 12:00:00,'NoneType' object has no attribute '_id'
2012-03-20 12:00:00,Failed to get customisation
2012-05-19 12:00:00,Failed to get customisation
2013-01-18 12:00:00,"HTTPSConnectionPool(host='api.eumetsat.int', port=443): Max retries exceeded with url: /epcs/customisations/6266d50c (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000028FDAAF2290>, 'Connection to api.eumetsat.int timed out. (connect timeout=None)'))"
2014-03-02 12:00:00,'NoneType' object has no attribute '_id'
2014-03-03 12:00:00,'NoneType' object has no attribute '_id'
2014-03-04 12:00:00,'NoneType' object has no attribute '_id'
2014-09-21 12:00:00,"not enough values to unpack (expected 1, got 0)"
2015-03-01 12:00:00,'NoneType' object has no attribute '_id'
2015-03-02 12:00:00,'NoneType' object has no attribute '_id'
2015-03-03 12:00:00,'NoneType' object has no attribute '_id'
2015-04-28 12:00:00,'NoneType' object has no attribute '_id'
2016-02-27 12:00:00,'NoneType' object has no attribute '_id'
2016-02-28 12:00:00,'NoneType' object has no attribute '_id'
2016-02-29 12:00:00,'NoneType' object has no attribute '_id'
2016-03-20 12:00:00,"not enough values to unpack (expected 1, got 0)"
2017-11-06 12:00:00,Failed to get customisation
2018-08-13 12:00:00,Failed to get customisation
2018-11-29 12:00:00,Failed to get customisation
2018-12-14 12:00:00,Failed to patch tailor delete
2019-01-29 12:00:00,'NoneType' object has no attribute '_id'
2019-09-30 12:00:00,Could not add customizations
2019-12-13 12:00:00,Failed to get customisation
2020-03-04 12:00:00,"not enough values to unpack (expected 1, got 0)"
2020-07-25 12:00:00
2011-11-08 12:00:00,Failed to get customisation
2011-12-30 12:00:00,"not enough values to unpack (expected 1, got 0)"
2012-04-09 12:00:00,Failed to get tailor download
2012-06-25 12:00:00,'NoneType' object has no attribute '_id'
2012-09-13 12:00:00,Failed to patch tailor delete
2013-05-10 12:00:00,"HTTPSConnectionPool(host='api.eumetsat.int', port=443): Max retries exceeded with url: /epcs/customisations?product_paths=https%3A%2F%2Fapi.eumetsat.int%2Fdata%2Fdownload%2F1.0.0%2Fcollections%2FEO%253AEUM%253ADAT%253AMSG%253ACLM%2Fproducts%2FMSG3-SEVI-MSGCLMK-0100-0100-20130510123000.000000000Z-NA&access_token=7b4f4d82-5d74-3f2c-8ff7-18574a22a3bf&chain_config=%7B%22id%22%3A+%22cloud_seviri%22%2C+%22product%22%3A+%22MSGCLMK%22%2C+%22format%22%3A+%22netcdf4%22%2C+%22name%22%3A+%22cloud_seviri%22%2C+%22description%22%3A+%22%22%2C+%22projection%22%3A+%22geographic%22%2C+%22filter%22%3A+%7B%22bands%22%3A+%5B%22cloud_mask%22%5D%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020EB391A110>, 'Connection to api.eumetsat.int timed out. (connect timeout=None)'))"
2013-08-18 12:00:00,'NoneType' object has no attribute '_id'
2013-10-31 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations/aa1c602a
2014-08-18 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations?product_paths=https%3A%2F%2Fapi.eumetsat.int%2Fdata%2Fdownload%2Fcollections%2FEO%253AEUM%253ADAT%253AMSG%253ACLM%2Fproducts%2FMSG3-SEVI-MSGCLMK-0100-0100-20140818123000.000000000Z-NA&access_token=0b34dc47-bda0-3758-b79f-0a33e8dfebbd&chain_config=%7B%22id%22%3A+%22cloud_seviri%22%2C+%22product%22%3A+%22MSGCLMK%22%2C+%22format%22%3A+%22netcdf4%22%2C+%22name%22%3A+%22cloud_seviri%22%2C+%22description%22%3A+%22%22%2C+%22projection%22%3A+%22geographic%22%2C+%22filter%22%3A+%7B%22bands%22%3A+%5B%22cloud_mask%22%5D%7D%7D
2015-03-12 12:00:00,'NoneType' object has no attribute '_id'
2015-04-28 12:00:00,'NoneType' object has no attribute '_id'
2015-08-13 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations/729cd53b
2015-08-14 12:00:00,"not enough values to unpack (expected 1, got 0)"
2016-06-11 12:00:00,"HTTPSConnectionPool(host='api.eumetsat.int', port=443): Max retries exceeded with url: /epcs/customisations?product_paths=https%3A%2F%2Fapi.eumetsat.int%2Fdata%2Fdownload%2Fcollections%2FEO%253AEUM%253ADAT%253AMSG%253ACLM%2Fproducts%2FMSG3-SEVI-MSGCLMK-0100-0100-20160611123000.000000000Z-NA&access_token=7c0bd3d9-3784-3465-b9db-773f297f8066&chain_config=%7B%22id%22%3A+%22cloud_seviri%22%2C+%22product%22%3A+%22MSGCLMK%22%2C+%22format%22%3A+%22netcdf4%22%2C+%22name%22%3A+%22cloud_seviri%22%2C+%22description%22%3A+%22%22%2C+%22projection%22%3A+%22geographic%22%2C+%22filter%22%3A+%7B%22bands%22%3A+%5B%22cloud_mask%22%5D%7D%7D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001A51CB5D090>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))"
2016-09-10 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations?product_paths=https%3A%2F%2Fapi.eumetsat.int%2Fdata%2Fdownload%2Fcollections%2FEO%253AEUM%253ADAT%253AMSG%253ACLM%2Fproducts%2FMSG3-SEVI-MSGCLMK-0100-0100-20160910123000.000000000Z-NA&access_token=36c6b8e3-abfc-32c7-8cce-e1c947ae0e7f&chain_config=%7B%22id%22%3A+%22cloud_seviri%22%2C+%22product%22%3A+%22MSGCLMK%22%2C+%22format%22%3A+%22netcdf4%22%2C+%22name%22%3A+%22cloud_seviri%22%2C+%22description%22%3A+%22%22%2C+%22projection%22%3A+%22geographic%22%2C+%22filter%22%3A+%7B%22bands%22%3A+%5B%22cloud_mask%22%5D%7D%7D
2016-11-23 12:00:00,401 Client Error: Unauthorized for url: https://api.eumetsat.int/epcs/customisations/7c522d12
2017-04-19 12:00:00,"not enough values to unpack (expected 1, got 0)"
2018-03-29 12:00:00,'NoneType' object has no attribute '_id'
2018-12-17 12:00:00,401 Client Error: Unauthorized for url: https://api.eumetsat.int/epcs/download?path=MSGCLMK-FP-0de6e58f%2FMSGCLMK_20181217T123000Z_20181217T123000Z_epct_0de6e58f_FP.nc
2019-03-02 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations/59d1a9d6
2019-03-03 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations?product_paths=https%3A%2F%2Fapi.eumetsat.int%2Fdata%2Fdownload%2Fcollections%2FEO%253AEUM%253ADAT%253AMSG%253ACLM%2Fproducts%2FMSG4-SEVI-MSGCLMK-0100-0100-20190303123000.000000000Z-NA&access_token=8aa90dce-5648-36e1-81c4-a80e05d2d831&chain_config=%7B%22id%22%3A+%22cloud_seviri%22%2C+%22product%22%3A+%22MSGCLMK%22%2C+%22format%22%3A+%22netcdf4%22%2C+%22name%22%3A+%22cloud_seviri%22%2C+%22description%22%3A+%22%22%2C+%22projection%22%3A+%22geographic%22%2C+%22filter%22%3A+%7B%22bands%22%3A+%5B%22cloud_mask%22%5D%7D%7D
2020-01-13 12:00:00,'NoneType' object has no attribute '_id'
2020-04-02 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations/8288e84c
2020-06-12 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations/3f76ae29
2020-06-13 12:00:00,500 Server Error: Internal Server Error for url: https://api.eumetsat.int/epcs/customisations?product_paths=https%3A%2F%2Fapi.eumetsat.int%2Fdata%2Fdownload%2Fcollections%2FEO%253AEUM%253ADAT%253AMSG%253ACLM%2Fproducts%2FMSG4-SEVI-MSGCLMK-0100-0100-20200613123000.000000000Z-NA&access_token=83ed0914-a677-38f8-bc96-912be1269a55&chain_config=%7B%22id%22%3A+%22cloud_seviri%22%2C+%22product%22%3A+%22MSGCLMK%22%2C+%22format%22%3A+%22netcdf4%22%2C+%22name%22%3A+%22cloud_seviri%22%2C+%22description%22%3A+%22%22%2C+%22projection%22%3A+%22geographic%22%2C+%22filter%22%3A+%7B%22bands%22%3A+%5B%22cloud_mask%22%5D%7D%7D
